steps:

  - id: "Instalação do App calculaRaizQuadradaGo"
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'app']
    env: ['GOPATH=.']
    
  - id: 'Executando o App calculaRaizQuadradaGo'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v','./...']
    env: ['GOPATH=.']

  - id: "Efetuando o Build da Imagem"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/go-hpa",
        "-f",
        "./dockerfile",
        ".",
      ]

  - id: "Efetuando o Push da Imagem"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/go-hpa"]

  - id: "Deploying K8S"
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'GCP/deployment.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel'